# Generated by Django 5.0.1 on 2025-11-27 18:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(verbose_name="تاریخ ایجاد"),
        ),
    ]
